### ISSUE TITLE
When using Configuration per output, bar does not rerender when you turn the monitor off and on again

### ISSUE THREAD

**Issue by alexthebuilder** [Alexays/Waybar#160]
I have Waybar setup to render on one of my three monitors. When I turn the monitor off I get the below message.

Bar removed from output: DP-1
Workspaces: Unable to receive IPC header
Mode: Unable to receive IPC header
Window: Unable to receive IPC header

Once I turn my monitor back on the bar does not show up. The process still exists but I have to terminate it and start a new one.

**Comment by Alexays** [comment]
@alexthebuilder Can you confirm that is fixed with 01cec9fcb7a0b14cfb7aa9ee34de138aad137359 :)

**Comment by alexthebuilder** [comment]
Tested it and I got the same result. 

I watched the logs this time and noticed that the below errors happen after I start the monitor.

Workspaces: Unable to receive IPC header
Mode: Unable to receive IPC header
Window: Unable to receive IPC header

**Comment by Alexays** [comment]
These errors are normal, before the Configuration per output implementation, did it work?

**Comment by alexthebuilder** [comment]
No the bar still does not appear. But waybar is still running.

**Comment by Alexays** [comment]
@alexthebuilder I'm not able to reproduce it, any tips?

**Comment by alexthebuilder** [comment]
Mind sending me any info on how I could get more debug info for this? Is there a way to get the bars current location similar to the startup location?

Bar Configured (width: 3840, height:40) for output: DP-1 

I'm not sure if there is an option to print out some runtime debug info so that I can help.

**Comment by malramsay64** [comment]
I am also having what I think is the same issue, Waybar doesn't return only after something appears to go to a sleep state. I replicate the issue by running
```bash
 swaymsg "output * dpms off"; sleep 12; swaymsg "output * dpms on"
```
On my system when sleeping for a shorter length of time the bug does not appear. I can see the waybar process is still running, just nothing displayed on the screen.

Happy to provide any additional information, I just don't know where to find anything relevant.

**Comment by Alexays** [comment]
@malramsay64 I'm unable to reproduce the issue with this command, can you provide your waybar config?

**Comment by malramsay64** [comment]
My Waybar config is [here](https://github.com/malramsay64/dotfiles/blob/ba7833d57f0b78411e322e2ea0513a152c00155a/config/waybar/config)

**Comment by malramsay64** [comment]
I can also replicate this issue by unplugging then replugging the monitor, which might be more widely replicable.

**Comment by Alexays** [comment]
I found out why, can someone try without custom modules and tell me if that works?

**Comment by alexthebuilder** [comment]
I'm traveling for business this week so won't be able to test it until Saturday. But I am using custom modules for sure so I'll be able to help when I get back.

**Comment by malramsay64** [comment]
I can confirm that removing any custom modules does fix this behaviour.

**Comment by alexthebuilder** [comment]
I can verify that removing the custom module renders the bar again as well.

**Comment by Alexays** [comment]
Fixed with 90d89fe9742fec690677fc6965d28b25df8fc14f
