### ISSUE TITLE
fails to launch

### ISSUE THREAD

**Issue by EysseW** [Alexays/Waybar#1677]
https://github.com/Alexays/Waybar/issues/812 but the error is: error while loading shared libraries: libfmt.so.8: cannot open shared object file: No such file or directory

**Comment by EysseW** [comment]
There's not much more to it honestly

**Comment by EysseW** [comment]
I have tried fmt, fmt-git, waybar, waybar-git, hyprland-waybar-git, nothing seems to work. I am on base arch btw.

**Comment by bg2908** [comment]
Rebuild `waybar` with `fmt 9.x` wont fix the issue, so downgrading `fmt` back to `8.1.1-2` is what works for me for now.

**Comment by asas1asas200** [comment]
Duplicated, #1675 .
If waybar attempts to find libfmt.8.so, that means you are using an old version.
The arch package has rebuilt for libfm9, make sure you correctly update your packages or try to build from source.

**Comment by EysseW** [comment]
I've got fmt 9.1.0-1 and waybar 0.9.13-2. These should just work together, shouldn't they?

**Comment by asas1asas200** [comment]
Sorry for typo. Edited just now.
Are you update by `-Syyu` and kill all the waybar processes then restart?

**Comment by bg2908** [comment]
In my case, `fmt 9.1.0-1` and `waybar 0.9.13-2` not work together. I reboot the machine after install these two and waybar not work, it would still try to find libfmt.so.8
Try to install `waybar-git` from aur with `fmt 9.1.0-1` and still got the same error.

**Comment by asas1asas200** [comment]
What is the order in which you installed it?
The runtime dependency is according to your current libs to build the target.
Install the latest version fmt at first then install the waybar if you want to build from source.

**Comment by bg2908** [comment]
Yes, I install the latest version `fmt` first then install `waybar-git` from aur. It did not worked. It would still try to find libfmt.so.8

But manual download and build `waybar` from source worked.

**Comment by EysseW** [comment]
Manual build of waybar doesn't work for me. I haven't tried a manual build of fmt, as I don't know how to. It's not documented

**Comment by asas1asas200** [comment]
> Manual build of waybar doesn't work for me. I haven't tried a manual build of fmt, as I don't know how to. It's not documented

Just clone this repo, then follow the steps below:
```
meson build
ninja -C build
./build/waybar
```

These steps also in the README.

**Comment by EysseW** [comment]
I did exactly that. No luck....

**Comment by Devarth123** [comment]
i can confirm this issue can be fixed by downgrading spdlog and libfmt

**Comment by EysseW** [comment]
Well how do I do this? There is no documentation for compiling fmt on their GitHub. And even if I nail to do so, how do I intergrade a library package into my system?

**Comment by Devarth123** [comment]
I am glad u asked @EysseW,
First download the older version of packages locally 
make sure u uninstall spdlog and fmt before doing this
links:
- https://cdn.discordapp.com/attachments/1016033172066156674/1016033345425125417/spdlog-1.10.0-2-x86_64.pkg.tar.zst 
- https://cdn.discordapp.com/attachments/1016033172066156674/1016033345425125417/spdlog-1.10.0-2-x86_64.pkg.tar.zst 

then run this as root
```
pacman -U path/to/the/two/files/you/installed
```
and you done, it should work now.

**Comment by EysseW** [comment]
Those links are the exact same.

**Comment by Devarth123** [comment]
my bad here is the other one  https://cdn.discordapp.com/attachments/1016033172066156674/1016033531195043932/fmt-8.1.1-2-x86_64.pkg.tar.zst

**Comment by AtlasC0R3** [comment]
Confirming, `community/waybar` will fail to launch, complaining that it can't find libfmt.so.8, however installing `aur/waybar-git` works flawless out of the box.
Interesting note, though: `chaotic-aur/waybar-experimental-git` does not work either (same error), however `aur/waybar-experimental-git` does.

Bottom line is, given that this seems to be an Arch-centric issue, compile it yourself (or don't upgrade `fmt`), as Chaotic AUR and mainstream doesn't compile with fmt9 in mind.

**Comment by JBenda** [comment]
Hey ho, yep, the problem with the distributed packaged is currently wrong binding. But also with the new `fmt` library, there is a compile error because the `std::filesystem::path` in `src/config.cpp` line 33 and 40 cannot be formatted. With a `path.string()` this can be fixed, or maybe something else to add support for `std::filesystem::path`.

A hotfix for people who want to work with fmt9 and way bar could use this hotfix temporary ^^
https://gist.github.com/JBenda/934a62398e0d1e7a775eeea47385fff2#file-waybarfmthotfix-patch

**Comment by Vagahbond** [comment]
Hey I was having the same issue but building from source (on master) today worked !

**Comment by JBenda** [comment]
Yes it was fixed 3 day ago with commit:
 https://github.com/Alexays/Waybar/commit/03ca8de6d744e9f52803a5d324ddbee822a9d045

**Comment by AtlasC0R3** [comment]
I believe the state of this issue as of right now is that:
- It's Arch-specific
- This issue only affects mainstream builds (those fetched using pacman, including the community and chaotic-aur repo)
- Building waybar using the AUR (or from the git source manually) works

So I suppose we are waiting for the aforementioned commit to become in an official update?

**Comment by EysseW** [comment]
> Yes it was fixed 3 day ago with commit: [03ca8de](https://github.com/Alexays/Waybar/commit/03ca8de6d744e9f52803a5d324ddbee822a9d045)

It still gives me the exact same error when I try to compile from latest source.

**Comment by Alexays** [comment]
@EysseW Did you still have errors?

**Comment by EysseW** [comment]
I did still experience the same issue before doing a clean install a couple of weeks ago. No issue on fresh install.

**Comment by nathanchere** [comment]
I'm getting the same thing now

> waybar: error while loading shared libraries: libfmt.so.9: cannot open shared object file: No such file or directory

libfmt was just updated to 10.0

I was using `waybar-hyprland` in AUR which doesn't seem to be updated that frequently.  Using `waybar-hyprland-git` as suggested above fixed it for me. Just noting it here in case anyone else comes across the same.

Given that it has been a recurring issue for years and libfmt is not all that big relatively speaking, is it worth considering compiling libfmt into waybar instead of linking to it?
