### ISSUE TITLE
font color problem

### ISSUE THREAD

**Issue by TAforever** [Alexays/Waybar#1741]
Today I compiled waybar-git and on most modules the color began to match the color of the background. Version 0.9.13 does not have this problem.
![waybar-git](https://user-images.githubusercontent.com/52626363/196939558-c13e18ba-facf-4d91-9568-c6d49b42e718.png)

**Comment by TAforever** [comment]
Here is version 0.9.13
![waybar](https://user-images.githubusercontent.com/52626363/196939772-f5acc623-042e-4ab9-8395-7beb85d706e5.png)

**Comment by danielrparks** [comment]
This happens with the default style as well:
![image](https://user-images.githubusercontent.com/42898924/197031432-bcf7795b-2a85-44b7-9532-69e88e0af09b.png)

**Comment by frkli1965** [comment]
Related to issue #1726?

**Comment by danielrparks** [comment]
Looks like it's related. I bisected it to b8322c4b4b023d8e6fbe8b6bf4100d6c60a06e42 which is from the same PR referenced in that issue (#1120 ). Note that for me, this is affecting even non-custom modules.

**Comment by tpeacock19** [comment]
```css
label:disabled,
button:disabled {
  color: inherit;
  background-image: none;
}
```

It seems like any module that does not have an "on-click" value in the config shows up as a disabled button. The above fixed this issue for me. Alternatively, you can add `"on-click": "true",` and it should pick up existing button styles.

**Comment by frkli1965** [comment]
Thanks tpeacock19 ...

Appending "on-click"; "true" to the config file helped to resolve the 'memory' module's font color for me whereas altering the 'style.css' with the provided suggestions didn't.

Decided to drop the "custom-menu" module as it's no longer supported it seems.

Kind regards,

**Comment by Alexays** [comment]
@pinselimo Can we add something like in #1738 to handle this issue?

**Comment by bklaase** [comment]
> ```css
> label:disabled,
> button:disabled {
>   color: inherit;
>   background-image: none;
> }
> ```
> 
> It seems like any module that does not have an "on-click" value in the config shows up as a disabled button. The above fixed this issue for me. Alternatively, you can add `"on-click": "true",` and it should pick up existing button styles.

that improves it, but the colors are still muted. As if maybe opacity is lowered as well

**Comment by tpeacock19** [comment]
I've found a more robust solution that may work for you. You'll have to add `all: unset` as the first declaration in these two rules:

```css
button {
  all: unset;
  ...[other css declarations]...
}
label {
  all: unset;
  ...[other css declarations]...
}
```

The `all: unset` rules seems to put everything back to default. It should cover all variations between themes.

**Comment by Alexays** [comment]
3cf027fc567c343f5523b7b08476a467d5248b37 Should fix the pb
Can someone try?

**Comment by TAforever** [comment]
> [3cf027f](https://github.com/Alexays/Waybar/commit/3cf027fc567c343f5523b7b08476a467d5248b37) Should fix the pb Can someone try?

The change happened, but still there is an error.
![waybar_grim](https://user-images.githubusercontent.com/52626363/199730254-da04cd31-9e42-4803-ae76-f24d1525e00e.png)

**Comment by hajosattila** [comment]
Same problem here. Waybar 0.9.13 vs 0.9.15

![scrn-2022-11-03-14-52-19](https://user-images.githubusercontent.com/1567493/199739166-c8a0ac42-a6ae-4706-9817-eb4b599c53d3.png)

![scrn-2022-11-03-14-52-09](https://user-images.githubusercontent.com/1567493/199739131-43bab331-ea90-4c50-aae8-cdfe8f9b19f1.png)

- Arch
- Sway WM

**Comment by danielrparks** [comment]
I'm still having the same problem with the default style as well.
![image](https://user-images.githubusercontent.com/42898924/199748842-aff67990-55b7-486b-9f57-203e3cce2643.png)

**Comment by Alexays** [comment]
And with 92cc01f?

**Comment by danielrparks** [comment]
I still have the same problem with 92cc01f .

**Comment by TAforever** [comment]
> And with [92cc01f](https://github.com/Alexays/Waybar/commit/92cc01f40149292d315456f7e5bbdad6dc099caf)?

Returned to the previous state.
![new_waybar_grim](https://user-images.githubusercontent.com/52626363/199756332-0c97e326-b4ae-42a0-8b4b-17447cc2d1ed.png)

**Comment by Alexays** [comment]
And with latest one 3030850?
Sorry for the mess..

**Comment by roland-rollo** [comment]
> And with latest one [3030850](https://github.com/Alexays/Waybar/commit/3030850b225863d2433590a796aa043d382df810)? Sorry for the mess..

Still grey.
![ps_20221104085308](https://user-images.githubusercontent.com/44477799/199921224-77f980fb-a4f7-4ef1-8b0a-6dfd84f1ab65.png)

**Comment by roland-rollo** [comment]
So with last comm
![ps_20221104220740](https://user-images.githubusercontent.com/44477799/200084439-949e0a1a-6b72-49a4-885e-db96fb5ea15d.png)
it, battery icon changed and with it, it's color to white. :P

**Comment by danielrparks** [comment]
The latest commit didn't work for me either.

**Comment by TAforever** [comment]
For the sake of interest, I decided to launch river with waybar in BSPWM and there is no such problem there. Maybe this information will be useful to you.
![river_X](https://user-images.githubusercontent.com/52626363/200176446-3fd72276-4b9e-496f-a20f-e641a3625bb6.png)

**Comment by TAforever** [comment]
And so: by experience, I realized that the problem lies in the GTK theme. For some reason, the font color started to depend on the theme. I installed the Gruvbox-Material-Dark theme instead of Qogir-dark as I have in BSPWM and there is no problem with the font.
![20221106_17h40m58s_grim](https://user-images.githubusercontent.com/52626363/200177580-db203d1d-8d72-4564-9afe-ef47a29e45f5.png)

**Comment by TAforever** [comment]
> And so: by experience, I realized that the problem lies in the GTK theme. For some reason, the font color started to depend on the theme. I installed the Gruvbox-Material-Dark theme instead of Qogir-dark as I have in BSPWM and there is no problem with the font. ![20221106_17h40m58s_grim](https://user-images.githubusercontent.com/52626363/200177580-db203d1d-8d72-4564-9afe-ef47a29e45f5.png)

I also want to note that as you can see, the tags module broke with this theme (they became too wide).

**Comment by tpeacock19** [comment]
> And so: by experience, I realized that the problem lies in the GTK theme.

Yes, I'm not sure there can be a solution implemented by Waybar since I imagine the theme will be applied after its loaded. The `all: unset` should be in the default configuration and perhaps highlighted in the wiki as a fix for this issue.

**Comment by TAforever** [comment]
> > And so: by experience, I realized that the problem lies in the GTK theme.
> 
> Yes, I'm not sure there can be a solution implemented by Waybar since I imagine the theme will be applied after its loaded. The `all: unset` should be in the default configuration and perhaps highlighted in the wiki as a fix for this issue.

@Alexays this seems to be the solution to the problem.

**Comment by danielrparks** [comment]
Indeed, adding

```css
* {
    all: unset;
}
```

to my configuration causes it to start working at 92cc01f40149292d315456f7e5bbdad6dc099caf.

Sorry about that! It didn't occur to me that my gtk theme would be applied after waybar's style changes.

**Comment by Alexays** [comment]
Closed as reverted
