### ISSUE TITLE
Some modules color seem to be hardcoded to grey in 0.9.15

### ISSUE THREAD

**Issue by itaranto** [Alexays/Waybar#1764]
After updating to `0.9.15` the `#cpu`, `#memory`, `#disk`, `#temperature`, `#battery` and `#language` modules have a grey color and cannot be changed:

![image](https://user-images.githubusercontent.com/11463919/199722940-b1ccad20-b5e7-4392-b502-92d6f9c194b2.png)

[style.css](https://gitlab.com/itaranto/dotfiles/-/blob/master/config/waybar/style.css):

```css
* {
  border: none;
  border-radius: 0;
  min-height: 0;
}

window#waybar {
  background: @unfocused_borders;
  color: @theme_fg_color;
  font: 13px "Source Code Pro", "Font Awesome 6 Free Solid", "Font Awesome 6 Brands";
}

#workspaces button {
  padding: 0 10px;
  background: transparent;
  color: @theme_fg_color;
}

#workspaces button.focused {
  background: @theme_bg_color;
  border-bottom: 3px solid @theme_fg_color;
  color: @theme_fg_color;
}

#workspaces button.urgent {
  background: @theme_fg_color;
  color: @theme_selected_bg_color;
}

#mode {
  margin: 0 4px;
  padding: 0 4px;
  background: @theme_fg_color;
  color: @unfocused_borders;
  font: 13px "Noto Sans";
}

#window{
  font: 13px "Noto Sans";
}

#pulseaudio, #network, #cpu, #memory, #disk, #temperature, #battery, #language, #clock, #tray {
  margin: 0 4px;
  padding: 0 2px;
}

#tray {
  font: 13px "Noto Sans";
}
```
[config.jsonc](https://gitlab.com/itaranto/dotfiles/-/blob/master/config/waybar/config.common.jsonc):

```jsonc
{
  "height": 24,
  "modules-left": [
    "sway/workspaces",
    "sway/mode"
  ],
  "modules-center": [
    "sway/window"
  ],
  "modules-right": [
    "pulseaudio",
    "network",
    "cpu",
    "memory",
    "disk",
    "temperature",
    "battery",
    "sway/language",
    "clock",
    "tray"
  ],
  "sway/window": {
    "icon": false,
    "max-length": 100
  },
  "pulseaudio": {
    "format": "{icon} {volume}%",
    "format-muted": " ",
    "format-bluetooth": "{icon} {volume}%",
    "format-bluetooth-muted": " ",
    "format-icons": {
      "default": [
        "",
        "",
        ""
      ]
    },
    "on-click": "pavucontrol"
  },
  "network": {
    "format-ethernet": " {ifname}",
    "format-wifi": " {essid}",
    "format-linked": " {ifname} (No IP)",
    "format-disconnected": "⚠ Disconnected",
    "format-alt": "{ifname}: {ipaddr}/{cidr}"
  },
  "cpu": {
    "format": " {usage}%",
  },
  "memory": {
    "format": " {}%"
  },
  "disk": {
    "path": "/home",
    "format": " {percentage_used}%"
  },
  "temperature": {
    "interval": 2,
    "critical-threshold": 80,
    "format": "{icon} {temperatureC}°C",
    "format-icons": [
      "",
      "",
      ""
    ]
  },
  "battery": {
    "interval": 60,
    "states": {
      "warning": 30,
      "critical": 15
    },
    "format": "{icon} {capacity}%",
    "format-icons": [
      "",
      "",
      "",
      "",
      ""
    ]
  },
  "sway/language": {
    "format": " {short}",
    "tooltip-format": "{long}"
  },
  "clock": {
    "format": " {:%H:%M}",
    "format-alt": " {:%Y-%m-%d}",
    "tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>"
  },
  "tray": {
    "spacing": 10
  }
}
```

**Comment by Laurent2916** [comment]
Same for me.
It seems every module without an `on-click` attribute are grey.
Added `"on-click": ""` to every affected modules as a temporary fix.

**Comment by Alexays** [comment]
https://github.com/Alexays/Waybar/commit/3cf027fc567c343f5523b7b08476a467d5248b37 Should fix the pb
Can someone try?

**Comment by itaranto** [comment]
> [3cf027f](https://github.com/Alexays/Waybar/commit/3cf027fc567c343f5523b7b08476a467d5248b37) Should fix the pb Can someone try?

It seems it didn't work (at least with my config):

![image](https://user-images.githubusercontent.com/11463919/199731281-545eae76-d57d-404c-8157-18538237a3cf.png)

This also brought up a padding issue it seems, but that's different discussion, I guess.

**Comment by ordy** [comment]
> [3cf027f](https://github.com/Alexays/Waybar/commit/3cf027fc567c343f5523b7b08476a467d5248b37) Should fix the pb Can someone try?

Tried as well that build doesn't work without the extra lines in the `style.css`.

In your commit you seem to change the default to button but in this case only the `label:disable` set to `all: unset` seems to have an effect on the colors.

**Comment by EuCaue** [comment]
> Same for me. It seems every module without an `on-click` attribute are grey. Added `"on-click": ""` to every affected modules as a temporary.

This worked for me.

**Comment by roland-rollo** [comment]
> [3cf027f](https://github.com/Alexays/Waybar/commit/3cf027fc567c343f5523b7b08476a467d5248b37) Should fix the pb Can someone try?

It doesn't fix anything. I'm at 92cc01f40149292d315456f7e5bbdad6dc099caf and problem still exist.

**Comment by WhyNotHugo** [comment]
Funny, it's not a problem with these modules:

```
#custom-systemd,
#custom-mic,
#mode,
#custom-khal,
#pulseaudio,
#battery,
```

Only clock is grey for me.

**Comment by WhyNotHugo** [comment]
Still present on r2251.92cc01f4

**Comment by itaranto** [comment]
> Funny, it's not a problem with these modules:
> 
> ```
> #custom-systemd,
> #custom-mic,
> #mode,
> #custom-khal,
> #pulseaudio,
> #battery,
> ```
> 
> Only clock is grey for me.

In my case I see several modules in grey, check out the screenshot in the issue's description.

**Comment by roland-rollo** [comment]
For me grey are brightness, cpu, memory, temperature and clock.

**Comment by itaranto** [comment]
Just for the record, `#mode` is also has grey `color` in my case.

**Comment by ordy** [comment]
@itaranto looking at your `style.css` you don't seem to define a color on your grayed out modules, so could it be that they'd set to the default "disabled" label color?

**Comment by Yutsuten** [comment]
I restored my previous styling (fixes this issue and #1763) by adding this:

```css
button {
    border: none;
}

label:disabled,
button:disabled {
    color: inherit;
}

button:hover {
    background: inherit;
}

```

**Comment by itaranto** [comment]
> @itaranto looking at your `style.css` you don't seem to define a color on your grayed out modules, so could it be that they'd set to the default "disabled" label color?

I'm not defining any color in any of these:

```css
#pulseaudio, #network, #cpu, #memory, #disk, #temperature, #battery, #language, #clock, #tray {
  margin: 0 4px;
  padding: 0 2px;
}
```

Yet only `pulseaudio`, `network` and `clock` seem to inherit `color` from "somewhere", the rest appear grey.

Maybe those selectors used to inherit from `#window#waybar` in 0.9.13, but now it haschanged, was I relying on a bad behaviour?

Anyway... setting them explicitely doesn't work either:

```
#pulseaudio, #network, #cpu, #memory, #disk, #temperature, #battery, #language, #clock, #tray {
  margin: 0 4px;
  padding: 0 2px;
  color: #ff0000;
}
```

![image](https://user-images.githubusercontent.com/11463919/199974705-c779f233-efaa-4591-a57a-d695317b35c6.png)

**Comment by rmfnogueira** [comment]
[3cf027f](https://github.com/Alexays/Waybar/commit/3cf027fc567c343f5523b7b08476a467d5248b37) did not fix it for me. Adding "on-click": "" seems to work for now.

**Comment by WhyNotHugo** [comment]
From what I can tell, the issue is that these labels are now all buttons, and GTK overrides the colours of buttons to be gre when disabled. In this case, they're "disabled" when they have no on-click.

Mostly describing the problem better; not sure of a clean solution.

**Comment by JohnTheCoolingFan** [comment]
Same for me:
![image](https://user-images.githubusercontent.com/43478602/201047442-1ca987fe-a233-4f2c-8f15-b424dd4ac3a1.png)
Originally it was very light gray
```css
#clock,
#battery,
#cpu,
#memory,
#disk,
#temperature,
#backlight,
#network,
#pulseaudio,
#custom-media,
#tray,
#mode,
#idle_inhibitor,
#mpd {
    padding: 0 10px;
    margin: 0 4px;
    color: #dfdfdf;
}
```

**Comment by To1ne** [comment]
I've git-bisected it down to it first happening in b8322c4b4b023d8e6fbe8b6bf4100d6c60a06e42. But I assume you already figured that out. 

But for what's it worth, it doesn't happen for me no more on 3718902b9d3a1a9bd6e2a1e05328a02e369b63b6.

**Comment by TheTumultuousUnicornOfDarkness** [comment]
> I restored my previous styling (fixes this issue and #1763) by adding this:
> 
> ```css
> button {
>     border: none;
> }
> 
> label:disabled,
> button:disabled {
>     color: inherit;
> }
> 
> button:hover {
>     background: inherit;
> }
> ```

Thank you very much, it also restored my previous styling!

**Comment by stefonarch** [comment]
>Adding "on-click": "" seems to work for now.

Confirmed, except for a custom module which is still grey.  I had temp and memory grey.

**Comment by Macellatore** [comment]
I'm experiencing the bug too.
In my case it seems it's affecting ony the modules which both:
* have a on-click effect configured
* have the default text colour

![screenshot_2022-11-17_17:44:49](https://user-images.githubusercontent.com/37865855/202506581-15ddc24e-cdf5-494f-ac3d-f0c3f0ef6bc4.png)

In the screenshot: 
* the visible grey modules have not a "on-click" specified.
* the visible yellow modules do have a "on-click" specified.
* the "invisible" modules would normally be grey, and they do have a "on-click" specified; they can be seen by hovering the mouse over them, as the background colour changes to white:

![screenshot_2022-11-17_17:50:16](https://user-images.githubusercontent.com/37865855/202507797-9a999dee-6cf7-4b87-b44b-4e5a8f6e5c85.png)

I'm not so convinced by the suggested workaround as it would disable all the on-click effects.
I can provide my config files if needed.

**Comment by itaranto** [comment]
> From what I can tell, the issue is that these labels are now all buttons, and GTK overrides the colours of buttons to be gre when disabled. In this case, they're "disabled" when they have no on-click.
> 
> Mostly describing the problem better; not sure of a clean solution.

So, how about making all modules clickable? Shouldn't that fix this issue without weird hacks in the CSS?

**Comment by Alexays** [comment]
Closed as reverted
